### ISSUE TITLE
Cutscene bug

### ISSUE THREAD

**Issue by owoqueoriginal** [Poobslag/turbofat#1023]
In the latest android version, this cutcene wouldn't end, I tapped everywhere, I tried a new save and the same happened
![Screenshot_20210830-200839](https://user-images.githubusercontent.com/43577045/131422661-dbe75088-f0bb-47ea-a418-847b6ead11c6.png)

**Comment by Poobslag** [comment]
Oh no! Thanks for the heads up, I'm sorry. I'll fix it soon!

**Comment by Poobslag** [comment]
@owoqueoriginal I've fixed the bug and uploaded a new version to itch.io, and released a new version on GitHub too! https://github.com/Poobslag/turbofat/releases/tag/v0.2901
