### ISSUE TITLE
I can't get inside the restaurant (android version)

### ISSUE THREAD

**Issue by owoqueoriginal** [Poobslag/turbofat#1187]
If I try to get inside or a cutscene has to play in it, the game crashes
I tried this on a new save just in case and the same happens

**Comment by Poobslag** [comment]
Thanks for the report, I'll investigate this!

**Comment by Poobslag** [comment]
I've fixed the crash. This applied to all versions of the game and was not specific.

Thanks for your diligence in trying the game with a new save, and thanks for the bug report!
