### ISSUE TITLE
Ghosts for textured block pieces don't match

### ISSUE THREAD

**Issue by Cheeseness** [Poobslag/turbofat#1790]
In 0.5111, I'm seeing ghost blocks that don't match the texture of blocks in this level with classic Tetrominoes (can't recall the name of the level -_- )

![image](https://user-images.githubusercontent.com/1570520/203704736-6d90b341-9c48-4b3c-8e9a-4872d862eaeb.png)

**Comment by Poobslag** [comment]
Fixed by #1775, thanks for the report!
